### PR TITLE
Add support badges

### PR DESCRIPTION
**Pull request by Eeems**
This'll have to wait a little bit until https://github.com/toltec-dev/toltec/pull/712 is merged and makes it's way into toltec stable next week.

### CODE REVIEW

**Comment by msencer** [comment]
@Eeems do you think it's ready now?

**Comment by Eeems** [comment]
> @Eeems do you think it's ready now?

The required changes have to get into toltec stable first

**Comment by Eeems** [comment]
@msencer it should be good to go now

**Comment by mkschulze** [comment]
Hey, can we get this in yet?

**Pull request merged**
